apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
spec:
  type: pubsub.redis
  metadata:
  - name: redisHost
    value: kubernetes.docker.internal:6379
  - name: redisPassword
    value: ""
  - name: processingTimeout
    # Zero set here to allow local debug without message retries
    value: 0
